name: Triggered workflow from POST req
on:
  workflow_dispatch:

jobs:
  deploy_qa:
    environment: qa
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14']

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Create env file
        run: | 
          cat > .env << EOF
          ${{secrets.ENV}}
          EOF

      - name: Create Dockerfile for deployment
        run: |
          cat > Dockerfile << EOF
          ${{secrets.DOCKER_FILE_DEPLOY}}
          EOF

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: us-west-2

      # - name: Deploy Severless
      #   uses: hdev14/sls-deploy-action@main
      #   with:
      #     awsAccessKeyID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     stage: "qa"
      #     region: "us-west-2"

      # - name: Serverless AWS authentication
      #   run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install NPM dependencies
        run: npm install && npm install -g serverless

      - name: Deploy Lambda functions
        run: sls deploy --stage qa --region us-west-2 --verbose