name: Triggered workflow from POST req
on:
  workflow_dispatch:

jobs:
  deploy_qa:
    environment: qa
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14']
    env:
      NODE_ENV: 'qa'
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_REGION: ${{secrets.AWS_REGION}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      DB_HOST: ${{secrets.DB_HOST}}
      DB_USER: ${{secrets.DB_USER}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: qa
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - run: npm run deploy:qa