name: Deploy lambda
on:
  repository_dispatch:
    types: [redeploy]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          branch: ${{ github.event.client_payload.branch }}
      - run: echo ${{ github.event.client_payload.branch }}