name: Triggered workflow from POST req
on:
  push:
    branches:
      - qa
  workflow_dispatch:

jobs:
  deploy_qa:
    environment: qa
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14']

    steps:
      # - name: checkout code
      #   uses: actions/checkout@v2
        
      # - name: Setup node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.node }}

      # - name: Create env file
      #   run: | 
      #     cat > .env << EOF
      #     ${{secrets.ENV}}
      #     EOF

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      #     aws-region: us-west-2

      # - name: Install NPM dependencies
      #   run: npm install -g serverless && npm i -D serverless-dotenv-plugin 

      - name: Deploy Lambda functions
        run: ${{ github.event.type == 'PushEvent' && 'es un push event' || echo github.event.type  }}
        # run: sls deploy --stage qa --region us-west-2 --verbose --force