name: Manually triggered workflow
on:
  workflow_dispatch:
    # inputs:
    #   name:
    #     description: 'Person to greet'
    #     required: true
    #     default: 'Mona the Octocat'
    #   home:
    #     description: 'location'
    #     required: false
    #     default: 'The Octoverse'

jobs:
  deploy_qa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14']
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm run deploy:qa