name: Triggered workflow from POST req
on:
  workflow_dispatch:

jobs:
  deploy_qa:
    environment: qa
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14']
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: us-west-2 

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm run deploy:qa
        env:
            NODE_ENV: 'qa'
            AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
            AWS_REGION: ${{secrets.AWS_REGION}}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            DB_HOST: ${{secrets.DB_HOST}}
            DB_USER: ${{secrets.DB_USER}}